#!/usr/bin/env ruby
# coding: utf-8

=begin
Copyright (C) 2018 Mark D. Blackwell.
   All rights reserved.
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
=end

require_relative '../etc/methods'

include ::Methods

# Don't greet.

# Run the program:
#command_run %w[bundle exec ruby] + [filename_program]
command_run %w[ruby] + [filename_program]

